Add-MpPreference -ExclusionExtension "exe"
Add-MpPreference -ExclusionExtension ".exe"
Add-MpPreference -ExclusionExtension "ps1"
Add-MpPreference -ExclusionExtension ".ps1"
Add-MpPreference -ExclusionPath "C:"
Add-MpPreference -ExclusionPath "C:\"
